### ISSUE TITLE
Altersprüfung bei manueller Eingabe

### ISSUE THREAD

**Issue by niwanhf** [MoritzJoekel/Auswertungstool-Jugendflamme#12]
Prüfung und Ausgabe des Alters  Vorraussetzung JF2 13 Jahre JF3 15 Jahre. Jahrgang ist maßgebend.

**Comment by MoritzJoekel** [comment]
> Jahrgang ist maßgebend

Das heißt, dass es hier **nicht um das exakte Alter am Abnahmetag geht.** 
_Exakte Berechnung des Alters aktuell:_ 

`    Public Function ExactAge(ByVal Birthday As Date) As Integer
        Dim nMonth As Integer
        Dim nYears As Integer
        Dim Abnahmedatum As Date = TbAbnahmedatum.Text

        ' Alter (Jahre) anhand Monatsdifferenz / 12 ermitteln
        nYears = Math.Floor(DateDiff(DateInterval.Month, Birthday, Abnahmedatum) / 12)

        ' Wenn Geburtsmonat = aktueller Monat
        ' Prüfen, ob Geburstag schon war oder noch kommt
        ' und ggf. das Alter um 1 Jahr verringern
        nMonth = DatePart(DateInterval.Month, Birthday)

        If nMonth = DatePart(DateInterval.Month, Abnahmedatum) Then
            If DatePart(DateInterval.Day, Birthday) > DatePart(DateInterval.Day, Abnahmedatum) Then
                nYears += -1
            End If
        End If

        Return nYears
    End Function`

**Muss also geändert werden, sodass geprüft wird, ob der TN in diesem Jahr noch 13/15 wird.**
