### ISSUE TITLE
Prüfung des maximalen Alters

### ISSUE THREAD

**Issue by niwanhf** [MoritzJoekel/Auswertungstool-Jugendflamme#13]
Prüfung ob am Veranstaltungstag der Teilnehmer 18 Jahre alt ist. Entscheidend ist das reale Geburtsdatum .

**Comment by MoritzJoekel** [comment]
> Entscheidend ist das reale Geburtsdatum

Heißt das, dass hier auch das **exakte Alter am Abnahmetag** geprüft werden soll oder wieder der **Jahrgang**? @niwanhf

**Comment by niwanhf** [comment]
Exaktes Alter

**Comment by MoritzJoekel** [comment]
048c4ce  mit der Bitte um Test.

http://moritzjoekel.bplaced.net/JuFla

**Comment by MoritzJoekel** [comment]
Aber ein TN, der zu Alt / zu Jung ist, kann garnicht importiert werden. Daher ist das doch garnicht notwendig...
