### ISSUE TITLE
Shortcuts

### ISSUE THREAD

**Issue by MoritzJoekel** [MoritzJoekel/Auswertungstool-Jugendflamme#15]
## Shortcuts
Mögliche **Anwendungsziele** von Tastenkürzeln:

- Neue Mannschaft

- Neuer Teilnehmer

- Wettbewerbseingabe

**Weitere?? @niwanhf **

#6 --> Kennzeichnung von Shortcuts

**Comment by niwanhf** [comment]
einen um in die Wettberbsauswertung zu kommen 

welche für die verschiedenenen Druckmöglichkeiten
